version: "3.8"

services:
  langflow:
    image: langflowai/langflow:${LANGFLOW_TAG} # or another version tag on https://hub.docker.com/r/langflowai/langflow 
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "${LANGFLOW_PORT}:7860"
    depends_on:
      - postgres
      - nextcloud
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
    volumes:
      - ./cache/langflow/data:/app/langflow
      - ${DATA_PATH}:/data
    networks:
      langflow_network:
        ipv4_address: 10.5.0.1

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    expose:
      - 5432
    volumes:
      - ./cache/langflow/postgres:/var/lib/postgresql/data
    networks:
      langflow_network:
        ipv4_address: 10.5.0.2

  nextcloud:
    image: nextcloud:30.0.4-fpm
    container_name: nextcloud
    networks:
      langflow_network:
        ipv4_address: 10.5.0.3
    depends_on:
      - nextclouddb
      - redis
    ports:
      - ${NEXTCLOUD_PORT}:80
    volumes:
      - ./nextcloud/custom-apps:/var/www/html/custom_apps
      - ./nextcloud/config:/var/www/html/config
      - ${DATA_PATH}:/var/www/html/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=redis

  nextclouddb:
    image: mariadb:11.6-ubi
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      langflow_network:
        ipv4_address: 10.5.0.4
    volumes:
      - ./cache/nextcloud/db:/var/lib/mysql
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      
  redis:
    image: redis:7.2.7-alpine3.21
    container_name: redis
    volumes:
      - ./cache/nextcloud/redis-data:/data  
    networks:
      langflow_network:
        ipv4_address: 10.5.0.5
  
networks:
  langflow_network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/24
         gateway: 10.5.0.255
